name: Deploy to DO serverless functions

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v5

      - name: Install DO CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Install serverless DO CLI
        run: doctl serverless install

      - name: Connect to functions namespace
        env:
          DO_FUNCTIONS_NAMESPACE: ${{ secrets.DO_FUNCTIONS_NAMESPACE }}
        run: doctl serverless connect "$DO_FUNCTIONS_NAMESPACE"

      - name : Deploy functions
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          doctl serverless deploy . --verbose 
